### PR TITLE
Code "Editor"

### PR DESCRIPTION
**Pull request by joyheron**
In this PR I am attempting to create a component `editor` which shows two code examples 'input' and 'output' next to each other because this is a common pattern that occurs in our documentation (input JSX to HTML or input JSX to HTML). 

I'm not overly attached to the name `editor` for the component, but I couldn't think of a better name because I was thinking of the MacDown editor or the CodiMD editor, where users type into the left hand side and the results are shown on the right hand side. In the long term, I think it could be possible to really make it an editor with a REPL on the left hand side and the output on the right hand side, but that doesn't have priority right now.

I currently wrote the component using pure CSS. In the long run, I would probably port this to SCSS because it would require repeating query selectors less often and might look cleaner.

I also wrote the component so that it really is only dependent on the `.editor` class and bound the styles for the left-hand side and right-hand side to the `:first-child` and `:last-child` selectors within the `.editor` container.

Screen Shot 2020-02-11 at 16 09 56

### CODE REVIEW

**Comment by joyheron** [comment]
I am thinking of trying to add two wrapper classes within the `.editor` container, so that the styles for left and write are bound to those classes instead of the `.editor > *:first-child` selector. My reasoning is that if I have a bit more control over the HTML, the labels for the left-hand side and right-hand side will no longer be hard encoded within the CSS file (I really don't like that).

**Comment by joyheron** [comment]
@FND Do you think you could give some feedback about this component? I have a feeling it is not yet 100% finished, but I would like some feedback about the visual presentation and the implementation as it now is.

**Comment by FND** [comment]
It certainly looks excellent! (I've allowed myself to attach a screenshot to your OP for reference.)

I'm somewhat surprised fenced code blocks still work within raw HTML; typically Markdown rendering is disabled inside such blocks. But if it works, it works.

The implementation looks alright to me, though I've only given it a cursory look for the moment. I agree `.editor` is a bit awkward (I'm not sure we'll ever manage to set up a REPL), but that's a minor detail. 

This is a significant improvement over the status quo, so if you're confident WRT maintainability, I'd say ship it.

**Comment by joyheron** [comment]
Thanks for the feedback! I am going to rebase and then maybe do some restructuring of the Sass files. I think I would like to start pulling the component specific CSS into component files, even when we are not yet using a Macro in order to instantiate the component. 

And I think I will sleep one night to see if I can come up with a better name than "editor".

**Comment by FND** [comment]
Perhaps "code mirror"? (I belatedly realized that's [already taken](https://codemirror.net), sort of, but that doesn't mean we can't use it for a local component anyway.)

**Comment by joyheron** [comment]
Maybe I could Germanify it and call it a `code-spiegel` 🤔

**Comment by joyheron** [comment]
Boring (but true) would probably be `.code-example`

But maybe I will go with that. Because boring is not always a bad thing.

**Comment by FND** [comment]
💯 👍

**Comment by joyheron** [comment]
Ok, I restructured the SCSS files so that we use component SCSS files whenever we use components (we already had a few, but we didn't have a preprocessor before). And I renamed the component to `code-example`.

Now I am satisfied :)

**Review by FND — APPROVED** [review]
:shipit: 👏

**Comment by moonglum** [comment]
This is so cool. Awesome work, @joyheron 👌

**Comment by joyheron** [comment]
And merging.... 😁

**Pull request merged**
