### PR TITLE
Added some webfonts from Google fonts

### PR DESCRIPTION
**Pull request by joyheron**
With the help of colleagues with design skills, I have selected two web fonts to use for the website: Sarabun as a sans-serif, and 'Fira Code' for monospace text.

A note here is that the current code blocks are still styled using `prism.css` and do not yet use 'Fira Code'. However, I want to do my own styling for the code blocks because I want to build a custom component for displaying the code, so that will occur in a next step.

### CODE REVIEW

**Comment by FND** [comment]
Generally speaking, I'm opposed to custom fonts, due to performance concerns and because I wouldn't want users to be tracked by third parties like Google (plus there are likely GDPR implications). It's often - though not always - unnecessary navel gazing, optimizing for creators' rather than users' needs.

Having said my piece, I won't veto this.

**Comment by joyheron** [comment]
I do understand your viewpoint about custom fonts, but I think if we want a really nicely designed site we need to use some more professional fonts. Your point about the Google tracking is a good point which I hadn't considered. Should I download the fonts and serve them from our site directly to hopefully avoid Google tracking?

**Comment by FND** [comment]
Yeah, avoiding Google's CDN would be a decent compromise - assuming the fonts' licenses permit this?

I'm not sure what serving fonts involves though, given weirdness about formats and all that. 🤷‍♂ (Preferably using an npm package rather than dumping font files in the repo, if possible.)

**Comment by joyheron** [comment]
@FND I've added `faucet-pipeline-static` and `faucet-pipeline-sass` to copy the font assets from npm repositories. I decided to make an explicit faucet-config to copy over each font file, because I do not want to serve all of the font-files that are available. This is also for performance reasons: we don't need to serve all the files to the user. I prefer selecting a limited number of font-styles and only serving those to the users.

I have checked in the asset files generated by faucet because we are currently checking in all of our assets / html files that we generate.

**Comment by FND** [comment]
Makes sense to me.

Just one clarification: Since you're not using fingerprinted assets, i.e. hard-coding file names in `.scss` and `.jsx`, why have a manifest at all?

**Comment by joyheron** [comment]
I still use the `asset-url` function in the Sass files so that I do not have to hardcode the links to the fonts in the Sass file. That's why I am using the manifest.

**Review by FND — APPROVED** [review]
Oh, my bad: I'd overlooked that.

Anyway, lgtm. :shipit:

**Comment by joyheron** [comment]
@FND Should I merge as is, or would you prefer that I squash it?

**Comment by FND** [comment]
I don't have strong opinions in this case: Both makes sense to me. (If it was me, I'd tweak the commit message, 72 chars and all that. But meh.)

**Comment by joyheron** [comment]
I will merge as is if you do not have a strong opinion about it. :)

**Pull request merged**
